### ISSUE TITLE
Cannot add more than 20 clozes

### ISSUE THREAD

**Issue by marcozer** [luzhe610/anki-enhanced-cloze#2]
Good evening, 

First of all I want to thank you for this awesome addon, 

I have been using this addon for the last six months, after adding 40 extra fields to be able to generate up to 60 clozes cards from one note. 
I then modified the script, replacing the default "20" to "60" ;  **however, even after updating the enhanced clozes in browser, it still won't generate more than  (the default) 20 cards**. 

I'm really sorry to tell you such things, that you might consider as easy to fix, but I don't have the coding knowledge required. 

I'm ready to pay for it, 

Thanks a lot, 

M-A

**Comment by Arthur-Milchior** [comment]
Do you still need help with that ? 
Fyi, this add-on has been ported recently to 2.1
